/**
 * Auth-specific error codes (003 FR-156). Only the subset relevant to
 * Phase 4's implemented scope is included — the FR-156 list also names
 * codes for onboarding/dashboard/OTP flows not built in this phase (see
 * docs/auth/TRACEABILITY.md).
 */
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_UNVERIFIED: 'AUTH_EMAIL_UNVERIFIED',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
  TOO_MANY_ATTEMPTS: 'AUTH_TOO_MANY_ATTEMPTS',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  REAUTH_REQUIRED: 'AUTH_REAUTH_REQUIRED',
  MFA_REQUIRED: 'AUTH_MFA_REQUIRED',
  MFA_INVALID_CODE: 'AUTH_MFA_INVALID_CODE',
  MFA_ALREADY_ENABLED: 'AUTH_MFA_ALREADY_ENABLED',
  MFA_NOT_ENABLED: 'AUTH_MFA_NOT_ENABLED',
  TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_ALREADY_USED: 'AUTH_TOKEN_ALREADY_USED',
  REFRESH_TOKEN_REUSE_DETECTED: 'AUTH_REFRESH_TOKEN_REUSE_DETECTED',
  EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
